name: CI-CD for Node.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: kashaankhan/kashaan-portfolio:${{ github.run_number }}

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests (Optional)
        run: npm test || echo "No tests found"

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERUSERNAME }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      - name: Update Deployment YAML and Push
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config user.name "iamkashaan"
          git config user.email "mohdkashaan2002.mk@gmail.com"

          if [ -f k8s/deployment.yml ]; then
            sed -i "s/replaceImageTag/${{ github.run_number }}/g" k8s/deployment.yml
            git add k8s/deployment.yml
            git diff --cached --quiet || git commit -m "Update deployment image to version ${{ github.run_number }}"
            git push https://${{ secrets.PAT_TOKEN }}@github.com/iamkashaan/kashaan-portfolio.git HEAD:main
          else
            echo "k8s/deployment.yml not found, skipping deployment update."
          fi
