apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iamkashaan/nodejsapp
     targetRevision: main
    path: argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: nodejs-app  # <-- changed from 'ls' to avoid conflict
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
